#!/usr/bin/with-contenv bash

# set php timezone
PHP_TZ=${PHP_TZ:-Europe/London}
sed -i "s#;date.timezone =.*#date.timezone = $PHP_TZ#" /etc/php/7.0/apache2/php.ini

# make folders if required
mkdir -p \
	"$DATADIR" \
	/config/{apache,log/mysql,log/zoneminder,mysql,zoneminder,keys} \
	/data/{zoneminder/events,zoneminder/exports,zoneminder/images,zoneminder/sounds} \
	/var/run/mysqld \
	/var/run/zoneminder \
	/var/cache/zoneminder


# copy apache config
[[ ! -f /config/apache/zoneminder.conf ]] && \
	cp /defaults/default.conf /config/apache/zoneminder.conf
cp /config/apache/zoneminder.conf /etc/apache2/sites-available/000-default.conf

# generate ssl keys
openssl req -x509 -nodes -days 4096 -newkey rsa:2048 -out /config/keys/cert.crt -keyout /config/keys/cert.key -subj "/C=US/ST=NY/L=New York/O=Zoneminder/OU=Zoneminder/CN=*"
chmod 777 /config/keys
# make links so we can use the standard config
rm -rf /etc/apache2/ssl/zoneminder.crt
ln -sf /config/keys/cert.crt /etc/apache2/ssl/zoneminder.crt
rm -rf /etc/apache2/ssl/zoneminder.key
ln -sf /config/keys/cert.key /etc/apache2/ssl/zoneminder.key

# cleanup stale pid and sock files
[[ -e /var/run/mysqld/mysqld.sock || -e /var/run/mysqld/mysqld.pid ]] && \
	rm -rf /var/run/mysqld/*
[[ -e /var/run/zoneminder/zmdc.sock || -e /var/run/zoneminder/zm.pid ]] && \
	rm -rf /var/run/zoneminder/*
[[ -e /var/run/apache2/apache2.pid ]] && \
	rm -rf /var/run/apache2/*

# setup custom cnf file
[[ ! -f /config/mysql/custom.cnf ]] && \
	cp /defaults/my.cnf /config/mysql/custom.cnf
[[ ! -L /etc/mysql/conf.d/custom.cnf && -f /etc/mysql/conf.d/custom.cnf ]] && \
	rm /etc/mysql/conf.d/custom.cnf
[[ ! -L /etc/mysql/conf.d/custom.cnf ]] && \
	ln -s /config/mysql/custom.cnf /etc/mysql/conf.d/custom.cnf

# set permissions
if [ -e /etc/mysql/debian.cnf ] ; then
	chown abc:abc /etc/mysql/debian.cnf
	chmod 644 /etc/mysql/debian.cnf
fi

chgrp -c abc /etc/zm/zm.conf
chmod 640 /etc/zm/zm.conf
chmod 755 /usr/bin/zmeventnotification.pl
chown abc:abc \
	/data
chown -R abc:abc \
	/config \
	/data/zoneminder
chmod -R 777 \
	/var/lib/apache2 \
	/var/run/mysqld \
	/var/run/zoneminder \
	/var/cache/zoneminder
